# Polynomial Regression

## Importing the libraries

In [ ]:
from glob import glob
import cv2
from matplotlib import pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate, KFold
from keras.losses import SparseCategoricalCrossentropy, CategoricalCrossentropy
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_curve, auc
from google.colab import drive
# import glob



from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Filename = "inceptionV3_nesfe_80px"

addressX = "/content/drive/MyDrive/dani/120/" + Filename + "_X.txt"

b = np.loadtxt(addressX)
X = b

In [ ]:
pos = 0
for temp in b:
  c = temp.tolist()
  if(pos == 0):
      X = [c]
      print(np.size(X))
  else:
    X.append(c)

  pos = pos + 1
  print("pos:")
  print(pos)

    

Streaming output truncated to the last 5000 lines.
pos:
45491
pos:
45492
pos:
45493
pos:
45494
pos:
45495
pos:
45496
pos:
45497
pos:
45498
pos:
45499
pos:
45500
pos:
45501
pos:
45502
pos:
45503
pos:
45504
pos:
45505
pos:
45506
pos:
45507
pos:
45508
pos:
45509
pos:
45510
pos:
45511
pos:
45512
pos:
45513
pos:
45514
pos:
45515
pos:
45516
pos:
45517
pos:
45518
pos:
45519
pos:
45520
pos:
45521
pos:
45522
pos:
45523
pos:
45524
pos:
45525
pos:
45526
pos:
45527
pos:
45528
pos:
45529
pos:
45530
pos:
45531
pos:
45532
pos:
45533
pos:
45534
pos:
45535
pos:
45536
pos:
45537
pos:
45538
pos:
45539
pos:
45540
pos:
45541
pos:
45542
pos:
45543
pos:
45544
pos:
45545
pos:
45546
pos:
45547
pos:
45548
pos:
45549
pos:
45550
pos:
45551
pos:
45552
pos:
45553
pos:
45554
pos:
45555
pos:
45556
pos:
45557
pos:
45558
pos:
45559
pos:
45560
pos:
45561
pos:
45562
pos:
45563
pos:
45564
pos:
45565
pos:
45566
pos:
45567
pos:
45568
pos:
45569
pos:
45570
pos:
45571
pos:
45572
pos:
45573
pos:
45574
pos:
45575
pos:
45576
pos

In [ ]:
x = np.array(X)
print(x.shape)

(47990, 2048)


In [ ]:
print(x[0])

[8.62739182 0.         0.80637556 ... 0.         0.         5.34406614]


## Importing the dataset

## eshteb


az 1400 goftim shoro kon
vali X=[]
neveshte bodim ehtemalan
yani X khali shode 
baad 18000 ta raft


In [7]:
images_path = {}
images_path["malignant"] = glob("/content/drive/MyDrive/dani/GasHisSDB/80/Abnormal/*.png")
images_path["benign"] = glob("/content/drive/MyDrive/dani/GasHisSDB/80/Normal/*.png")


images_class = {
    'benign' : 0,
    'malignant' : 1
}

import sys

from tensorflow.keras.applications import ResNet50
from keras.models import Model
import keras

pre_trained_models = {}


from tensorflow.keras.applications import InceptionV3
import numpy as np

pre_trained_models["InceptionV3"] = InceptionV3(weights='imagenet', pooling="avg", include_top=False)
for layer in pre_trained_models["InceptionV3"].layers:
    layer.trainable = False


# print(images_path["malignant"])
counter = 0

Y = []
Z = []
pos = 0
for label in images_path:
    counter = 0
    for image_path in images_path[label]:
        # print(counter, ' / ', all)
        counter += 1
        pos += 1
        if(pos > 47990):
          image = cv2.imread(image_path)
          image = cv2.resize(image,(224, 224))
          Z.append(image)
          
          if(counter % 10 == 0):

            if(counter % 500 == 0):      
              print("inja:")

              x = np.array(X)
              Filename = "inceptionV3_nesfe_80px"
              addressX = "/content/drive/MyDrive/dani/120/" + Filename + "_X.txt"
              np.savetxt(addressX, x, fmt='%s')

              print("savveeed at pos:")
              print(pos)


            temp = np.array(Z)
            

            feature_InceptionV3 = pre_trained_models["InceptionV3"].predict(temp)
            print(feature_InceptionV3)

            for b in feature_InceptionV3:
              c = b.tolist()
              if(pos == 0):
                  X =  [c]
                  print(np.size(X))
              else:
                X.append(c)


              print("shapeX:")
              o = np.array(X)
              print(o.shape)

              # pos += 1

            # print(X)
            Z = []
          

          Y.append(images_class[label])
          # print(sys.getsizeof(X)/1000000)
          print("counter:")
          print(counter)
          print("pos:")
          print(pos)
          print("label:" + label)
        else:
          continue



print(np.size(X))
print(np.size(Y))



Streaming output truncated to the last 5000 lines.
shapeX:
(54201, 2048)
shapeX:
(54202, 2048)
shapeX:
(54203, 2048)
shapeX:
(54204, 2048)
shapeX:
(54205, 2048)
shapeX:
(54206, 2048)
shapeX:
(54207, 2048)
shapeX:
(54208, 2048)
shapeX:
(54209, 2048)
shapeX:
(54210, 2048)
counter:
54210
pos:
54210
label:malignant
counter:
54211
pos:
54211
label:malignant
counter:
54212
pos:
54212
label:malignant
counter:
54213
pos:
54213
label:malignant
counter:
54214
pos:
54214
label:malignant
counter:
54215
pos:
54215
label:malignant
counter:
54216
pos:
54216
label:malignant
counter:
54217
pos:
54217
label:malignant
counter:
54218
pos:
54218
label:malignant
counter:
54219
pos:
54219
label:malignant
[[0.         0.         2.1956475  ... 0.         0.         3.7821293 ]
 [0.         0.         1.083142   ... 1.8226383  0.         0.        ]
 [0.8103156  0.2226396  0.3436902  ... 0.         0.         9.323984  ]
 ...
 [0.         0.         0.         ... 0.         0.         0.18759573]
 [0.        

In [8]:
x = np.array(X)
Filename = "inceptionV3_nesfe_80px"
addressX = "/content/drive/MyDrive/dani/120/" + Filename + "_X.txt"
np.savetxt(addressX, x, fmt='%s')

## Training the Linear Regression model on the whole dataset

In [ ]:
# from tensorflow.keras.applications.resnet50 import ResNet50
# from keras.models import Model
# import keras

x = np.array(X)
y = np.array(Y)
# pre_trained_models = {}
# pre_trained_models["ResNet50"] = ResNet50(include_top=False, input_shape=(224, 224, 3), pooling="avg", weights = 'imagenet')

# temp = 0
# for layer in pre_trained_models["ResNet50"].layers:
#     layer.trainable = False
#     temp += 1

# print("tedad:")
# print(temp)
# print(sys.getsizeof(pre_trained_models["ResNet50"].layers))
# print(pre_trained_models["ResNet50"].layers)

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=0)
# X_train = pre_trained_models["ResNet50"].predict(X_train)
# X_test = pre_trained_models["ResNet50"].predict(X_test)


# print("X_train:")
# print(X_train.shape)


# print(X_train)

# print("X_test:")
# print(X_test.shape)

print("x:")
print(x.shape)



# print("koltedad:")
# o = pre_trained_models["ResNet50"].predict(x)
# print(o.shape)
# print("kol:")
# print(o)






print(x[0])

x:
(33284, 2048)
[0.        0.        0.        ... 0.        0.        1.7934109]


VGG19

In [ ]:
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg19 import preprocess_input
import numpy as np

model = VGG19(weights='imagenet', pooling="avg", include_top=False)

features = model.predict(x)

print(features.shape)

80150528/80134624 [==============================] - 0s 0us/step


ValueError: ignored

DenseNet201

In [ ]:
from tensorflow.keras.applications import DenseNet201
from tensorflow.keras.applications.densenet import preprocess_input
import numpy as np

model = DenseNet201(weights='imagenet', pooling="avg", include_top=False)

features = model.predict(x)

print(features.shape)


74850304/74836368 [==============================] - 1s 0us/step
(80, 1920)


ResNet101

In [ ]:
from tensorflow.keras.applications.resnet import ResNet101
import numpy as np

model = ResNet101(include_top=False, input_shape=(224, 224, 3), pooling="avg", weights = 'imagenet')
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

171458560/171446536 [==============================] - 2s 0us/step
(80, 2048)


ResNet152

In [ ]:
from tensorflow.keras.applications.resnet import ResNet152
import numpy as np

model = ResNet152(include_top=False, input_shape=(224, 224, 3), pooling="avg", weights = 'imagenet')
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

234708992/234698864 [==============================] - 3s 0us/step
(80, 2048)


InceptionV3

In [ ]:
from tensorflow.keras.applications import InceptionV3
import numpy as np

model = InceptionV3(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

87924736/87910968 [==============================] - 1s 0us/step
(80, 2048)


InceptionResNetV2

In [ ]:
from tensorflow.keras.applications import InceptionResNetV2
import numpy as np

model = InceptionResNetV2(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

219070464/219055592 [==============================] - 2s 0us/step
(80, 1536)


MobileNet

In [ ]:
from tensorflow.keras.applications import MobileNet
import numpy as np

model = MobileNet(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

17235968/17225924 [==============================] - 0s 0us/step
(80, 1024)


NASNetMobile

In [ ]:

from tensorflow.keras.applications import NASNetMobile
import numpy as np

model = NASNetMobile(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

20004864/19993432 [==============================] - 0s 0us/step
(80, 1056)


EfficientNetB0

In [ ]:

from tensorflow.keras.applications import EfficientNetB0
import numpy as np

model = EfficientNetB0(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

16719872/16705208 [==============================] - 0s 0us/step
(80, 1280)


EfficientNetB1

In [ ]:

from tensorflow.keras.applications import EfficientNetB1
import numpy as np

model = EfficientNetB1(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

27033600/27018416 [==============================] - 0s 0us/step
(80, 1280)


EfficientNetB2

In [ ]:

from tensorflow.keras.applications import EfficientNetB2
import numpy as np

model = EfficientNetB2(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

31801344/31790344 [==============================] - 0s 0us/step
(80, 1408)


EfficientNetB3

In [ ]:

from tensorflow.keras.applications import EfficientNetB3
import numpy as np

model = EfficientNetB3(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

43950080/43941136 [==============================] - 0s 0us/step
(80, 1536)


EfficientNetB4

In [ ]:

from tensorflow.keras.applications import EfficientNetB4
import numpy as np

model = EfficientNetB4(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

71696384/71686520 [==============================] - 1s 0us/step
(80, 1792)


EfficientNetB5

In [ ]:

from tensorflow.keras.applications import EfficientNetB5
import numpy as np

model = EfficientNetB5(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

115277824/115263384 [==============================] - 1s 0us/step
(80, 2048)


EfficientNetB6

In [ ]:

from tensorflow.keras.applications import EfficientNetB6
import numpy as np

model = EfficientNetB6(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

165249024/165234480 [==============================] - 3s 0us/step
(80, 2304)


EfficientNetB7

In [ ]:

from tensorflow.keras.applications import EfficientNetB7
import numpy as np

model = EfficientNetB7(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

258088960/258076736 [==============================] - 3s 0us/step
(80, 2560)


DenseNet121

In [ ]:
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.applications.densenet import preprocess_input
import numpy as np

model = DenseNet121(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

29097984/29084464 [==============================] - 0s 0us/step
(80, 1024)


DenseNet169

In [ ]:
from tensorflow.keras.applications import DenseNet169
from tensorflow.keras.applications.densenet import preprocess_input
import numpy as np

model = DenseNet169(weights='imagenet', pooling="avg", include_top=False)
for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

51888128/51877672 [==============================] - 1s 0us/step
(80, 1664)


VGG16

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', pooling="avg", include_top=False)

for layer in model.layers:
    layer.trainable = False

features = model.predict(x)

print(features.shape)

58900480/58889256 [==============================] - 1s 0us/step
(80, 512)


## Training the Polynomial Regression model on the whole dataset

In [ ]:
result = {}
Classifier = XGBClassifier(learning_rate=0.9, n_estimators=150, random_state=0, seed=0, gamma=0)
Classifier.fit(X_train, Y_train)
Y_pred = Classifier.predict(X_test)
print("Accuracy score : ", accuracy_score(Y_test, Y_pred))
# print(X_train)
# print(X_test)
# print(Y_train)
# print(Y_test)

# print(Y_test)
# print(Y_pred)

Accuracy score :  0.6805527738834368


## Visualising the Linear Regression results